# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Pioneer Aero"
email: pioneeraero@gare.works
description: >- # this means to ignore newlines until 'baseurl:'
  Ardmore Specialised Aircraft Restoration
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.pioneeraero.co.nz" # the base hostname & protocol for your site, e.g. http://example.com
github_username: pioneeraero
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
#remote-theme: TankedThomas/airspace-jekyll
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-optional-front-matter
  - jekyll-paginate-v2
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-spaceship
# paginate: 8
imagesurl: "/assets/img/clients/"
thumbsurl: "/assets/img/clients/"

# Exclude from processing
exclude:
  - "*.code-workspace"
  - "*.gemspec"
  - "/contact-form/"
  - "/docs/"
  - "/licenses/"
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE.md"
  - "node_modules"
  - "README.md"
  - "reverse_markdown"
  - "archive_taxonomy.html"
  - "paginator.html"
  - "post_pagination.html"
  - "default.html.new"
  - "default.html.old"

# Always include in processing
keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

# Category descriptions (for archive pages)
descriptions:
  - cat: projects
    desc: "Our projects."

  - cat: news
    desc: "Our news."
# Google analytics
# ga_tracking_id: 'UA-XXXX-1'
############################################################
# Pagination
# The values here represent the defaults if nothing is set
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 5

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'news'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: '' 

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'
############################################################
# Auto-Pages
# The values here represent the defaults if nothing is set
autopages:

  # Site-wide kill switch, disable here and it doesn't run at all 
  enabled: false

  # Category pages, omit entire config element to disable
  categories: 
    # Optional, the list of layouts that should be processed for every category found in the site
    layouts: 
      - 'autopage_category.html'
    # Optional, the title that each category paginate page should get (:cat is replaced by the Category name)
    title: 'Posts in category :cat'
    # Optional, the permalink for the  pagination page (:cat is replaced), 
    # the pagination permalink path is then appended to this permalink structure
    permalink: '/category/:cat'
    # Optional, when true logging related to category pages will be supressed.
    silent: false
    slugify:
      mode: 'default'   # :cat is slugified. Modes: default, raw, pretty, ascii, latin
      case: false       # Whether to replace all uppercase letters with their lowercase counterparts

  # Collection pages, omit to disable
  collections:
    layouts: 
      - 'autopage_collection.html'
    title: 'Posts in collection :coll' # :coll is replaced by the collection name
    permalink: '/collection/:coll'
    silent: false
    slugify:
      mode: 'default'   # :coll is slugified.
      case: false 
  
  # Tag pages, omit to disable
  tags:
    layouts: 
      - 'autopage_tags.html'
    title: 'Posts tagged with :tag' # :tag is replaced by the tag name
    permalink: '/tag/:tag'
    silent: false
    slugify:
      mode: 'default'   # :tag is slugified.
      case: false
############################################################
# Comments via Staticman
comments:
  name: "Pioneer Aero"
  allowedFields: ['name', 'email', 'url', 'message']
  branch: "master"
  commitMessage: "New comment"
  filename: comment-{@timestamp}
  format: "yml"
  moderation: false
  path: "_data/comments/{options.slug}"
  requiredFields: ['name', 'email', 'message']
  transforms:
    email: "md5"
  generatedFields:
    date:
      type: date
      options:
        # format: "timestamp-seconds"
        format: "iso8601"
# Notification settings. When enabled, users can choose to receive notifications
# via email when someone adds a reply or a new comment. This requires an account
# with Mailgun, which you can get for free at http://mailgun.com.
#notifications:
  # Enable notifications
  #enabled: true

  # (!) ENCRYPTED
  #
  # Mailgun API key
  #apiKey: "1q2w3e4r"

  # (!) ENCRYPTED
  #
  # Mailgun domain (encrypted)
  #domain: "4r3e2w1q"
reCaptcha:
 enabled: false
#  siteKey: ""
#  secret: ""

