# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Pioneer Aero"
email: pioneeraero@gare.works
description: >- # this means to ignore newlines until 'baseurl:'
  Ardmore Specialised Aircraft Restoration
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.pioneeraero.co.nz" # the base hostname & protocol for your site, e.g. http://example.com
github_username: pioneeraero
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
#remote-theme: TankedThomas/airspace-jekyll
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-spaceship
paginate: 8
imagesurl: "/assets/img/clients/"
thumbsurl: "/assets/img/clients/"

# Exclude from processing
exclude:
  - "*.code-workspace"
  - "*.gemspec"
  - "/contact-form/"
  - "/docs/"
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE.md"
  - "node_modules"
  - "README.md"
  - "reverse_markdown"

# Always include in processing
keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."
# Google analytics
# ga_tracking_id: 'UA-XXXX-1'
